platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs


inputs:
- name: app
- name: ci-buildpacks

params:
  CF_API_URI:
  CF_USERNAME:
  CF_PASSWORD:
  CF_ORGANIZATION:
  CF_SPACE:
  BUILDPACK_NAME:

run:
  path: ci-buildpacks/tasks/push-app/task.sh
