resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
- name: cron-resource
  type: docker-image
  source:
    repository: cftoolsmiths/cron-resource

resources:
- name: pcf-pipelines
  type: git
  source:
    uri: https://github.com/pivotal-cf/pcf-pipelines.git
- name: ci-buildpacks
  type: git
  source:
    uri: https://github.com/vzickner/ci-buildpacks.git
- name: schedule
  type: cron-resource
  source:
    expression: "0 16 * * 1"
    location: "Europe/Berlin"
- name: first-week-schedule
  type: cron-resource
  source:
    expression: "0 9 1-7 * *"
    location: "Europe/Berlin"
- name: second-week-schedule
  type: cron-resource
  source:
    expression: "0 9 8-14 * *"
    location: "Europe/Berlin"
- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-webhook-url))
- name: buildpack-state-test
  type: s3
  source:
    bucket: ((aws-bucket))
    regexp: buildpack-state-test/state-(.*).txt
    access_key_id: ((aws-access-key-id))
    secret_access_key: ((aws-secret-access-key))
    region_name: eu-central-1

jobs:
- name: regulator
  plan:
  - aggregate:
    - get: schedule
      trigger: true
- name: test-regulator
  plan:
  - aggregate:
    - get: first-week-schedule
      trigger: true
    - get: ci-buildpacks
  - task: promote-buildpacks-on-test-only-monday
    file: ci-buildpacks/tasks/promote-buildpacks-on-test-only-monday/task.yml
    params:
      FLY_HOST: ((fly-host))
      FLY_TEAM: ((fly-team))
      FLY_USERNAME: ((fly-username))
      FLY_PASSWORD: ((fly-password))
      CF_API_URI: ((cf-api-uri))
      CF_USERNAME: ((cf-username))
      CF_PASSWORD: ((cf-password))
      PIPELINE: ((pipeline))
    on_success:
      put: buildpack-state-test
      params:
        file: buildpack-state-test/state-*.txt
- name: prod-regulator
  plan:
  - aggregate:
    - get: second-week-schedule
      trigger: true
    - get: ci-buildpacks
    - get: buildpack-state-test
      passed:
      - test-regulator
  - task: promote-buildpacks-on-prod-only-monday
    file: ci-buildpacks/tasks/promote-buildpacks-on-prod-only-monday/task.yml
    params:
      FLY_HOST: ((fly-host))
      FLY_TEAM: ((fly-team))
      FLY_USERNAME: ((fly-username))
      FLY_PASSWORD: ((fly-password))
      CF_API_URI: ((cf-api-uri))
      CF_USERNAME: ((cf-username))
      CF_PASSWORD: ((cf-password))
      PIPELINE: ((pipeline))
